import type { WorkProject } from "@/types"

export const PROJECTS: WorkProject[] = [
  {
    slug:        "urbanroots-ecommerce",
    title:       "UrbanRoots",
    category:    "E-Commerce + AI Automation",
    year:        "2025",
    tags:        ["Shopify", "AI Agents", "Email Flows"],
    gridRow:     1,
    gridSize:    "full",
    aspectRatio: "16/7",
    imagePrompt: "Dark editorial product shot of artisanal skincare bottles arranged on matte black stone surface, dramatic side lighting casting long amber shadows, one beam of warm golden light raking across the surface, shallow depth of field, cinematic 35mm grain, no text, --ar 16:7 --style raw",
    imageSrc:    "/images/work/urbanroots-ecommerce.jpg",
    stats:       [{ label: "Revenue growth", value: "8x" }, { label: "ROAS", value: "3.2x" }],
  },
  {
    slug:        "smilecare-dental",
    title:       "SmileCare",
    category:    "Digital Marketing + AI Chatbot",
    year:        "2024",
    tags:        ["Meta Ads", "AI Chatbot", "SEO"],
    gridRow:     2,
    gridSize:    "60",
    aspectRatio: "4/3",
    imagePrompt: "Overhead flat-lay of a modern dental clinic reception desk: clean white surfaces, a smartphone showing a sleek appointment app UI in teal and white, stethoscope, small succulent, all on pearl white background, clinical yet warm, natural window light from left, editorial photography --ar 4:3 --style raw",
    imageSrc:    "/images/work/smilecare-dental.jpg",
    stats:       [{ label: "Leads/month", value: "+340%" }, { label: "Ad ROAS", value: "4.1x" }],
  },
  {
    slug:        "zestbrew-brand",
    title:       "ZestBrew",
    category:    "Brand Identity + Packaging",
    year:        "2025",
    tags:        ["Brand", "Packaging", "Photography"],
    gridRow:     2,
    gridSize:    "40",
    aspectRatio: "3/4",
    imagePrompt: "Premium craft beverage cans floating against deep forest green background, amber condensation droplets on the metallic surface, dramatic macro lens shot with bokeh citrus elements, moody studio lighting with single overhead key light, rich colors, editorial packaging photography --ar 3:4 --style raw",
    imageSrc:    "/images/work/zestbrew-brand.jpg",
    stats:       [{ label: "Brand awareness", value: "+220%" }],
  },
  {
    slug:        "realtyone-proptech",
    title:       "RealtyOne",
    category:    "AI Agent + Web Platform",
    year:        "2025",
    tags:        ["Next.js", "AI Agent", "CRM"],
    gridRow:     3,
    gridSize:    "full",
    aspectRatio: "16/5",
    imagePrompt: "Ultra-wide architectural photography of a sleek Mumbai luxury residential building at blue hour, warm amber interior lights contrasting cool twilight sky, reflection in a wet cobblestone foreground, minimal composition, shot at f2.8 with anamorphic lens flares, no people, cinematic --ar 16:5 --style raw",
    imageSrc:    "/images/work/realtyone-proptech.jpg",
    stats:       [{ label: "Leads qualified by AI", value: "78%" }, { label: "Cost per lead", value: "-60%" }],
  },
  {
    slug:        "petalpath-dtoC",
    title:       "PetalPath",
    category:    "D2C Growth + Performance",
    year:        "2024",
    tags:        ["Meta Ads", "Email", "CRO"],
    gridRow:     4,
    gridSize:    "55-right",
    aspectRatio: "4/3",
    imagePrompt: "Intimate tabletop still life of pressed botanical flowers in a dark amber resin tray, warm dappled light filtering through sheer linen curtain, pale stone surface, one fresh garden rose cut stem beside the tray, shallow depth of field, melancholic beauty, analog film simulation --ar 4:3 --style raw",
    imageSrc:    "/images/work/petalpath-dtoc.jpg",
    stats:       [{ label: "MoM revenue growth", value: "+180%" }],
  },
]
